### ISSUE TITLE
Shader Crash

### ISSUE THREAD

**Issue by knupel** [StanLepunK/Rope_method#9]
https://github.com/knupel/Rope_examples/tree/master/SHADER_FX/fx_1_dither

https://github.com/knupel/Rope_examples/tree/master/SHADER_FX/fx_1_glitch

this two shader FX example cause a Processing crash, with Processing 4.0b7

```
RunnableTask.run(): A caught exception occured on thread main-Display-.macosx_nil-1-EDT-1: RunnableTask[enqueued true[executed false, flushed false, thread[0x6bd0a252, main-Display-.macosx_nil-1-EDT-1]], tTotal 0 ms, tExec 0 ms, tQueue 0 ms, attachment null, throwable java.lang.RuntimeException: Waited 5000ms for: <3515b402, 482e986d>[count 3, qsz 0, owner <main-FPSAWTAnimator#00-Timer0>] - <main-Display-.macosx_nil-1-EDT-1>]
java.lang.RuntimeException: Waited 5000ms for: <3515b402, 482e986d>[count 3, qsz 0, owner <main-FPSAWTAnimator#00-Timer0>] - <main-Display-.macosx_nil-1-EDT-1>
	at jogamp.common.util.locks.RecursiveLockImpl01Unfairish.lock(RecursiveLockImpl01Unfairish.java:198)
	at jogamp.newt.WindowImpl$ResizableAction.run(WindowImpl.java:2159)
	at jogamp.newt.DisplayImpl.runOnEDTIfAvail(DisplayImpl.java:447)
	at jogamp.newt.WindowImpl.runOnEDTIfAvail(WindowImpl.java:2859)
	at jogamp.newt.WindowImpl.setResizable(WindowImpl.java:2195)
	at com.jogamp.newt.opengl.GLWindow.setResizable(GLWindow.java:371)
	at processing.opengl.PSurfaceJOGL.lambda$setResizable$5(PSurfaceJOGL.java:436)
	at com.jogamp.common.util.RunnableTask.run(RunnableTask.java:125)
	at jogamp.newt.DefaultEDTUtil$NEDT.run(DefaultEDTUtil.java:375)
DefaultEDT.run(): Caught exception occured on thread main-Display-.macosx_nil-1-EDT-1: RunnableTask[enqueued false[executed true, flushed false, thread[0x6bd0a252, main-Display-.macosx_nil-1-EDT-1]], tTotal 5002 ms, tExec 5002 ms, tQueue 0 ms, attachment null, throwable java.lang.RuntimeException: Waited 5000ms for: <3515b402, 482e986d>[count 3, qsz 0, owner <main-FPSAWTAnimator#00-Timer0>] - <main-Display-.macosx_nil-1-EDT-1>]
java.lang.RuntimeException: Waited 5000ms for: <3515b402, 482e986d>[count 3, qsz 0, owner <main-FPSAWTAnimator#00-Timer0>] - <main-Display-.macosx_nil-1-EDT-1>
	at jogamp.common.util.locks.RecursiveLockImpl01Unfairish.lock(RecursiveLockImpl01Unfairish.java:198)
	at jogamp.newt.WindowImpl$ResizableAction.run(WindowImpl.java:2159)
	at jogamp.newt.DisplayImpl.runOnEDTIfAvail(DisplayImpl.java:447)
	at jogamp.newt.WindowImpl.runOnEDTIfAvail(WindowImpl.java:2859)
	at jogamp.newt.WindowImpl.setResizable(WindowImpl.java:2195)
	at com.jogamp.newt.opengl.GLWindow.setResizable(GLWindow.java:371)
	at processing.opengl.PSurfaceJOGL.lambda$setResizable$5(PSurfaceJOGL.java:436)
	at com.jogamp.common.util.RunnableTask.run(RunnableTask.java:125)
	at jogamp.newt.DefaultEDTUtil$NEDT.run(DefaultEDTUtil.java:375)
```

**Comment by knupel** [comment]
an other crash with 
https://github.com/knupel/Rope_examples/tree/master/IMAGE_PGRAPHICS/background_image

```
load shader: data/shader/fx_post/level.glsl
The pixels array is null.
52
OpenGL error 1282 at top endDraw(): invalid operation
RuntimeException: Cannot compile fragment shader:
ERROR: 0:82: Invalid call of 'mix' (not a function or subroutine uniform)
�
RuntimeException: Cannot compile fragment shader:
ERROR: 0:82: Invalid call of 'mix' (not a function or subroutine uniform)
�
```
